version: '3.8'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./packages/server/db:/docker-entrypoint-initdb.d/
  server:
    restart: always
    build: ./packages/server
    ports:
      - "3000:3000"


  client:
    restart: always
    build: ./packages/client
    ports:
      - "8080:80"
    volumes:
      - ./packages/client/src:/app/src
      - ./packages/client/public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
